import streamlit as st
from text_preprocessing_and_model import sentence_embedding_based_classifier, roberta_model_based_classifier

def main():
    """
    Main function to run the Streamlit web app.
    """
    st.title("AI Content Detector")
    st.write("Detect if content is generated by AI or written byHuman.")

    # Input text box
    text_input = st.text_area("Enter the content to classify:", height=200)

    model_dict = {
        "Transformer Based Embedding" : sentence_embedding_based_classifier,
        "Roberta Model" : roberta_model_based_classifier,
        "T5 Model" : sentence_embedding_based_classifier,
        "LSTM" : sentence_embedding_based_classifier,
        "Traditional Model" : sentence_embedding_based_classifier
    }

    # Create a dropdown for model selection
    model_options = list(model_dict.keys())
    selected_model = st.selectbox("Select Model", model_options)
    

    if st.button("Predict"):
        if text_input.strip():
            try:
                model = model_dict[selected_model]
                result = model(text_input)
                st.success(f"Prediction: {result}")
            except Exception as e:
                st.error(f"Error in prediction: {e}")
        else:
            st.warning("Please enter some text to classify!")


if __name__ == "__main__":
    main()
    
